word = "Weather"
print(word[0])
print(word[2])
print(word[-1])
print(word[-3])
print(word[2:4])
print(word[2:14])
print(word[2:-2])
# print(word[start:end:step])
print(word[2:4:-1])
print(word[4:2:-1])
print(word[5:1:-2])
print(word[-1:0:-1])
print(word[-1::-1])
print(word[::-1])